2012-10-04 01:15:00,036 ERROR [EJBVelocity] (Thread-16926) ::nobody::1569: ResourceManager : unable to find resource '/email/email_cust_deposit_release_en.vm' in any resource loader.
2012-10-04 01:15:00,036 ERROR [com.riavera.app.service.template.WTemplate] (Thread-16926) ::nobody::1569: cannot locate template '/email/email_cust_deposit_release_en.vm' - velocity exception: Unable to find resource '/email/email_cust_deposit_release_en.vm'
2012-10-04 01:15:00,036 ERROR [com.riavera.ejb.session.EventDispatcherBean] (Thread-16926) ::nobody::1569: exception handling queued event 26F1A4BDC0A8144733D0D500AAB0B7CB - will retry again later: com.riavera.exceptions.WNotFoundException: TEMPLATE_NOT_FOUND (9501): Cannot locate template
	at com.riavera.app.service.template.WTemplate.processTemplateToFile(WTemplate.java:358) [:]
	at sun.reflect.GeneratedMethodAccessor4552.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:157) [:6.0.0.GA]
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:96) [:6.0.0.GA]
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:88) [:6.0.0.GA]
2012-10-04 02:11:26,555 ERROR [org.jboss.ejb.plugins.LogInterceptor] (WorkerThread#3[192.168.20.71:49942])  TransactionRolledbackException in method: public abstract javax.ejb.EJBObject javax.ejb.Handle.getEJBObject() throws java.rmi.RemoteException, causedBy:: java.rmi.NoSuchObjectException: Could not activate; failed to restore state
	at org.jboss.ejb.plugins.AbstractInstanceCache.get(AbstractInstanceCache.java:134) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer.getEJBObject(StatefulSessionContainer.java:394) [:6.1.0.Final]
	at sun.reflect.GeneratedMethodAccessor3683.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at org.jboss.invocation.Invocation.performCall(Invocation.java:386) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer$ContainerInterceptor.invokeHome(StatefulSessionContainer.java:564) [:6.1.0.Final]
2012-10-04 02:11:26,559 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#3[192.168.20.71:49942])  couldn't get loginUserSF by handle: Could not activate; failed to restore state; nested exception is: 
	java.rmi.NoSuchObjectException: Could not activate; failed to restore state
2012-10-04 02:11:35,732 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#3[192.168.20.71:49942])  no service_config parameter wallet_bal_min_CAD defined!
2012-10-04 02:40:13,799 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#5[192.168.20.71:18333])  couldn't get loginUserSF by handle: Could not activate; failed to restore state; nested exception is: 
	java.rmi.NoSuchObjectException: Could not activate; failed to restore state
2012-10-04 02:40:13,823 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#5[192.168.20.71:18333])  bad: 
2012-10-04 02:40:13,823 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#5[192.168.20.71:18333])  invalidDataMap: {HOME_PHONE=45016}
2012-10-04 02:49:46,832 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#3[192.168.20.71:57699]) :miiscan-prod:74.198.9.115:tofoody::::0:  unable to find cust user:tofoodyNo such entity!
2012-10-04 02:50:22,104 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#3[192.168.20.71:57699]) :miiscan-prod:74.198.9.115:tofoody::::0:  unable to find cust user:tofoodyNo such entity!
2012-10-04 02:56:52,837 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#0[192.168.20.71:27861])  bad: 
2012-10-04 02:56:52,837 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#0[192.168.20.71:27861])  invalidDataMap: {OPERATIONAL_PASSWORD=1004, HOME_PHONE=45016}
2012-10-04 02:59:05,665 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#3[192.168.20.71:27870]) :MobileWallet:127.0.0.1:nnapp_fi_in::::0:  unable to find cust user:scottNo such entity!
2012-10-04 03:00:06,772 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#3[192.168.20.71:27870]) :MobileWallet:127.0.0.1:nnapp_fi_in::::0:  unable to find cust user:scott banhNo such entity!
2012-10-04 03:00:14,917 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#3[192.168.20.71:27870]) :MobileWallet:127.0.0.1:nnapp_fi_in::::0:  unable to find cust user:scottNo such entity!
2012-10-04 03:00:25,567 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#3[192.168.20.71:27870]) :MobileWallet:127.0.0.1:nnapp_fi_in::::0:  unable to find cust user:mr.banhNo such entity!
2012-10-04 04:50:00,095 ERROR [com.riavera.ejb.session.EventDispatcherBean] (Thread-16927) ::nobody::1639: unexpected exception processing callback for event 0904C523C0A81447668E37B60976341C: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [:1.6.0_33]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at com.riavera.ejb.session.EventDispatcherBean.finishAttempt(EventDispatcherBean.java:438) [:]
	at sun.reflect.GeneratedMethodAccessor4196.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
012-10-04 06:26:32,230 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#0[192.168.20.71:9297])  couldn't get loginUserSF by handle: Could not activate; failed to restore state; nested exception is: 
	java.rmi.NoSuchObjectException: Could not activate; failed to restore state
2012-10-04 06:26:32,247 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#0[192.168.20.71:9297])  couldn't get loginUserSF by handle: Could not activate; failed to restore state; nested exception is: 
	java.rmi.NoSuchObjectException: Could not activate; failed to restore state
012-10-04 06:45:00,079 ERROR [com.riavera.ejb.session.EventDispatcherBean] (Thread-16927) ::nobody::1650: unexpected exception processing callback for event 096AB109C0A814471CCFCFE2E900EA6A: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [:1.6.0_33]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at com.riavera.ejb.session.EventDispatcherBean.finishAttempt(EventDispatcherBean.java:438) [:]
	at sun.reflect.GeneratedMethodAccessor4196.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
012-10-04 08:50:46,923 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#3[192.168.20.71:36641]) :MobileWallet:127.0.0.1:nnapp_fi_in::::0:  unable to find cust user:cathycruz_myx@yahoo.comNo such entity!
2012-10-04 09:10:00,034 ERROR [EJBVelocity] (Thread-16927) ::nobody::1675: ResourceManager : unable to find resource '/email/email_cust_deposit_release_en.vm' in any resource loader.
2012-10-04 09:10:00,034 ERROR [com.riavera.app.service.template.WTemplate] (Thread-16927) ::nobody::1675: cannot locate template '/email/email_cust_deposit_release_en.vm' - velocity exception: Unable to find resource '/email/email_cust_deposit_release_en.vm'
2012-10-04 09:10:00,034 ERROR [com.riavera.ejb.session.EventDispatcherBean] (Thread-16927) ::nobody::1675: exception handling queued event 26F1A4BDC0A8144733D0D500AAB0B7CB - will retry again later: com.riavera.exceptions.WNotFoundException: TEMPLATE_NOT_FOUND (9501): Cannot locate template
	at com.riavera.app.service.template.WTemplate.processTemplateToFile(WTemplate.java:358) [:]
	at sun.reflect.GeneratedMethodAccessor4552.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:157) [:6.0.0.GA]
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:96) [:6.0.0.GA]
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:88) [:6.0.0.GA]
012-10-04 12:15:00,070 ERROR [com.riavera.ejb.session.EventDispatcherBean] (Thread-16925) ::nobody::1701: unexpected exception processing callback for event 0FC7BBF7C0A8144723A1E52CD6BC302E: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [:1.6.0_33]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at com.riavera.ejb.session.EventDispatcherBean.finishAttempt(EventDispatcherBean.java:438) [:]
	at sun.reflect.GeneratedMethodAccessor4196.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
012-10-04 13:01:10,139 ERROR [org.jboss.ejb.plugins.LogInterceptor] (WorkerThread#0[192.168.20.71:37922])  TransactionRolledbackException in method: public abstract javax.ejb.EJBObject javax.ejb.Handle.getEJBObject() throws java.rmi.RemoteException, causedBy:: java.rmi.NoSuchObjectException: Could not activate; failed to restore state
	at org.jboss.ejb.plugins.AbstractInstanceCache.get(AbstractInstanceCache.java:134) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer.getEJBObject(StatefulSessionContainer.java:394) [:6.1.0.Final]
	at sun.reflect.GeneratedMethodAccessor3683.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at org.jboss.invocation.Invocation.performCall(Invocation.java:386) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer$ContainerInterceptor.invokeHome(StatefulSessionContainer.java:564) [:6.1.0.Final]
2012-10-04 13:01:10,142 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#0[192.168.20.71:37922])  couldn't get loginUserSF by handle: Could not activate; failed to restore state; nested exception is: 
	java.rmi.NoSuchObjectException: Could not activate; failed to restore state
2012-10-04 13:10:00,591 WARN  [org.hibernate.util.JDBCExceptionReporter] (DefaultQuartzScheduler_Worker-1)  SQL Error: 1, SQLState: 23000
2012-10-04 13:10:00,591 ERROR [org.hibernate.util.JDBCExceptionReporter] (DefaultQuartzScheduler_Worker-1)  ORA-00001: unique constraint (OFFNET.XCHG_RATE_UNIQ) violated
2012-10-04 13:10:00,591 WARN  [org.hibernate.util.JDBCExceptionReporter] (DefaultQuartzScheduler_Worker-1)  SQL Error: 1, SQLState: 23000
2012-10-04 13:10:00,591 ERROR [org.hibernate.util.JDBCExceptionReporter] (DefaultQuartzScheduler_Worker-1)  ORA-00001: unique constraint (OFFNET.XCHG_RATE_UNIQ) violated
	at oracle.jdbc.driver.DatabaseError.throwBatchUpdateException(DatabaseError.java:629) [:Oracle JDBC Driver version - "11.1.0.7.0-Production"]
	at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:9409) [:Oracle JDBC Driver version - "11.1.0.7.0-Production"]
	at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:211) [:Oracle JDBC Driver version - "11.1.0.7.0-Production"]
	at org.jboss.resource.adapter.jdbc.CachedPreparedStatement.executeBatch(CachedPreparedStatement.java:476) [:6.1.0.Final]
	at org.jboss.resource.adapter.jdbc.WrappedStatement.executeBatch(WrappedStatement.java:774) [:6.1.0.Final]
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:70) [:3.6.6.Final]
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:268) [:3.6.6.Final]
2012-10-04 13:46:55,653 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#3[192.168.20.71:43150])  couldn't get loginUserSF by handle: Could not activate; failed to restore state; nested exception is: 
	java.rmi.NoSuchObjectException: Could not activate; failed to restore state
012-10-04 14:46:34,844 ERROR [com.riavera.ejb.session.PurchasingBean] (WorkerThread#4[192.168.20.71:56081]) ::nnapp_fi_in::1799: unsupported address field 'cust_name' in address set
2012-10-04 14:55:00,034 ERROR [EJBVelocity] (Thread-16926) ::nobody::1803: ResourceManager : unable to find resource '/email/email_cust_deposit_release_en.vm' in any resource loader.
2012-10-04 14:55:00,034 ERROR [com.riavera.app.service.template.WTemplate] (Thread-16926) ::nobody::1803: cannot locate template '/email/email_cust_deposit_release_en.vm' - velocity exception: Unable to find resource '/email/email_cust_deposit_release_en.vm'
2012-10-04 14:55:00,034 ERROR [com.riavera.ejb.session.EventDispatcherBean] (Thread-16926) ::nobody::1803: exception handling queued event 26F1A4BDC0A8144733D0D500AAB0B7CB - will retry again later: com.riavera.exceptions.WNotFoundException: TEMPLATE_NOT_FOUND (9501): Cannot locate template
	at com.riavera.app.service.template.WTemplate.processTemplateToFile(WTemplate.java:358) [:]
	at sun.reflect.GeneratedMethodAccessor4552.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:157) [:6.0.0.GA]
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:96) [:6.0.0.GA]
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:88) [:6.0.0.GA]
2012-10-04 15:04:51,316 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#0[192.168.20.71:26448]) :MIISCAN:127.0.0.1:victoria::M4H1J6::0:  unable to find cust user:victoriaNo such entity!
2012-10-04 16:54:23,352 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#5[192.168.20.71:53918]) :miiscan-prod:184.175.29.233:gotaybah@gmail.com::::0:  unable to find cust user:gotaybah@gmail.comNo such entity!
012-10-04 16:55:59,806 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#3[192.168.20.71:53922])  no service_config parameter wallet_bal_min_CAD defined!
2012-10-04 16:56:09,658 ERROR [com.riavera.ejb.session.PurchasingBean] (WorkerThread#6[192.168.20.71:29519]) ::nnapp_fi_in::1842: unsupported address field 'cust_name' in address set
2012-10-04 16:56:54,797 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#0[192.168.20.71:27889]) :miiscan-prod:184.175.29.233:gotayb@gmail.com::::0:  unable to find cust user:gotayb@gmail.comNo such entity!

