2012-10-08 00:10:00,014 DEBUG [org.hibernate.SQL] (Thread-16927) ::nobody::2683: select event0_.EVENT_GUID as EVENT1_118_0_, event0_.ATTEMPTS as ATTEMPTS118_0_, event0_.CALLBACK_METHOD as CALLBACK3_118_0_, event0_.ENTRY_DATE as ENTRY4_118_0_, event0_.ERROR_CODE as ERROR5_118_0_, event0_.LAST_ATTEMPT as LAST6_118_0_, event0_.LOCK_DATE as LOCK7_118_0_, event0_.LOCKED_BY as LOCKED8_118_0_, event0_.NEXT_ATTEMPT as NEXT9_118_0_, event0_.PARENT_EVENT_GUID as PARENT10_118_0_, event0_.REQUEST as REQUEST118_0_, event0_.RESPONSE as RESPONSE118_0_, event0_.STATE as STATE118_0_, event0_.TRANSACTION_REF as TRANSAC14_118_0_, event0_.TYPE as TYPE118_0_, event0_.VERSION as VERSION118_0_ from offnet.EVENT event0_ where event0_.EVENT_GUID=?
2012-10-08 00:10:00,020 DEBUG [org.hibernate.SQL] (Thread-16927) ::nobody::2684: select event0_.EVENT_GUID as EVENT1_118_0_, event0_.ATTEMPTS as ATTEMPTS118_0_, event0_.CALLBACK_METHOD as CALLBACK3_118_0_, event0_.ENTRY_DATE as ENTRY4_118_0_, event0_.ERROR_CODE as ERROR5_118_0_, event0_.LAST_ATTEMPT as LAST6_118_0_, event0_.LOCK_DATE as LOCK7_118_0_, event0_.LOCKED_BY as LOCKED8_118_0_, event0_.NEXT_ATTEMPT as NEXT9_118_0_, event0_.PARENT_EVENT_GUID as PARENT10_118_0_, event0_.REQUEST as REQUEST118_0_, event0_.RESPONSE as RESPONSE118_0_, event0_.STATE as STATE118_0_, event0_.TRANSACTION_REF as TRANSAC14_118_0_, event0_.TYPE as TYPE118_0_, event0_.VERSION as VERSION118_0_ from offnet.EVENT event0_ where event0_.EVENT_GUID=?
2012-10-08 00:10:00,077 ERROR [EJBVelocity] (Thread-16927) ::nobody::2684: ResourceManager : unable to find resource '/email/email_cust_deposit_release_en.vm' in any resource loader.
2012-10-08 00:10:00,077 ERROR [com.riavera.app.service.template.WTemplate] (Thread-16927) ::nobody::2684: cannot locate template '/email/email_cust_deposit_release_en.vm' - velocity exception: Unable to find resource '/email/email_cust_deposit_release_en.vm'
2012-10-08 00:10:00,078 ERROR [com.riavera.ejb.session.EventDispatcherBean] (Thread-16927) ::nobody::2684: exception handling queued event 26F1A4BDC0A8144733D0D500AAB0B7CB - will retry again later: com.riavera.exceptions.WNotFoundException: TEMPLATE_NOT_FOUND (9501): Cannot locate template
	at com.riavera.app.service.template.WTemplate.processTemplateToFile(WTemplate.java:358) [:]
	at sun.reflect.GeneratedMethodAccessor4552.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:157) [:6.0.0.GA]
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:96) [:6.0.0.GA]
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:88) [:6.0.0.GA]

2012-10-08 01:20:00,606 DEBUG [org.jboss.ejb.plugins.AbstractInstanceCache] (WorkerThread#3[192.168.20.71:43364])  Activation failure: javax.ejb.EJBException: Could not activate; failed to restore state
	at org.jboss.ejb.plugins.StatefulSessionFilePersistenceManager.activateSession(StatefulSessionFilePersistenceManager.java:343) [:6.1.0.Final]
	at org.jboss.ejb.plugins.StatefulSessionInstanceCache.activate(StatefulSessionInstanceCache.java:113) [:6.1.0.Final]
	at org.jboss.ejb.plugins.AbstractInstanceCache.doActivate(AbstractInstanceCache.java:458) [:6.1.0.Final]
	at org.jboss.ejb.plugins.StatefulSessionInstanceCache.doActivate(StatefulSessionInstanceCache.java:129) [:6.1.0.Final]
	at org.jboss.ejb.plugins.AbstractInstanceCache.get(AbstractInstanceCache.java:123) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer.getEJBObject(StatefulSessionContainer.java:394) [:6.1.0.Final]
	at sun.reflect.GeneratedMethodAccessor3683.invoke(Unknown Source) [:1.6.0_33]

2012-10-08 05:10:00,012 DEBUG [org.hibernate.SQL] (Thread-16925) ::nobody::2712: select event0_.EVENT_GUID as EVENT1_118_0_, event0_.ATTEMPTS as ATTEMPTS118_0_, event0_.CALLBACK_METHOD as CALLBACK3_118_0_, event0_.ENTRY_DATE as ENTRY4_118_0_, event0_.ERROR_CODE as ERROR5_118_0_, event0_.LAST_ATTEMPT as LAST6_118_0_, event0_.LOCK_DATE as LOCK7_118_0_, event0_.LOCKED_BY as LOCKED8_118_0_, event0_.NEXT_ATTEMPT as NEXT9_118_0_, event0_.PARENT_EVENT_GUID as PARENT10_118_0_, event0_.REQUEST as REQUEST118_0_, event0_.RESPONSE as RESPONSE118_0_, event0_.STATE as STATE118_0_, event0_.TRANSACTION_REF as TRANSAC14_118_0_, event0_.TYPE as TYPE118_0_, event0_.VERSION as VERSION118_0_ from offnet.EVENT event0_ where event0_.EVENT_GUID=?
2012-10-08 05:10:00,021 DEBUG [org.hibernate.SQL] (Thread-16925) ::nobody::2713: select event0_.EVENT_GUID as EVENT1_118_0_, event0_.ATTEMPTS as ATTEMPTS118_0_, event0_.CALLBACK_METHOD as CALLBACK3_118_0_, event0_.ENTRY_DATE as ENTRY4_118_0_, event0_.ERROR_CODE as ERROR5_118_0_, event0_.LAST_ATTEMPT as LAST6_118_0_, event0_.LOCK_DATE as LOCK7_118_0_, event0_.LOCKED_BY as LOCKED8_118_0_, event0_.NEXT_ATTEMPT as NEXT9_118_0_, event0_.PARENT_EVENT_GUID as PARENT10_118_0_, event0_.REQUEST as REQUEST118_0_, event0_.RESPONSE as RESPONSE118_0_, event0_.STATE as STATE118_0_, event0_.TRANSACTION_REF as TRANSAC14_118_0_, event0_.TYPE as TYPE118_0_, event0_.VERSION as VERSION118_0_ from offnet.EVENT event0_ where event0_.EVENT_GUID=?
2012-10-08 05:10:00,041 ERROR [com.riavera.ejb.session.EventDispatcherBean] (Thread-16925) ::nobody::2713: unexpected exception processing callback for event 0904C523C0A81447668E37B60976341C: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [:1.6.0_33]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at com.riavera.ejb.session.EventDispatcherBean.finishAttempt(EventDispatcherBean.java:438) [:]
	at sun.reflect.GeneratedMethodAccessor4196.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
, callbackMethod=MerchantApiBean.processResponse, errorCode=EVENT_CALLBACK_ERROR, nextAttempt=2012-10-09 05:10:00.047}
2012-10-08 05:10:00,049 DEBUG [org.hibernate.SQL] (Thread-16925) ::nobody::2713: update offnet.EVENT set ATTEMPTS=?, ERROR_CODE=?, LAST_ATTEMPT=?, LOCK_DATE=?, LOCKED_BY=?, NEXT_ATTEMPT=?, STATE=?, VERSION=? where EVENT_GUID=? and VERSION=?
, callbackMethod=MerchantApiBean.processResponse, errorCode=EVENT_CALLBACK_ERROR, nextAttempt=2012-10-09 05:10:00.047}
2012-10-08 05:17:10,482 DEBUG [org.jboss.ejb.plugins.AbstractInstanceCache] (WorkerThread#5[192.168.20.71:47311])  Activation failure: javax.ejb.EJBException: Could not activate; failed to restore state
	at org.jboss.ejb.plugins.StatefulSessionFilePersistenceManager.activateSession(StatefulSessionFilePersistenceManager.java:343) [:6.1.0.Final]
	at org.jboss.ejb.plugins.StatefulSessionInstanceCache.activate(StatefulSessionInstanceCache.java:113) [:6.1.0.Final]
	at org.jboss.ejb.plugins.AbstractInstanceCache.doActivate(AbstractInstanceCache.java:458) [:6.1.0.Final]
	at org.jboss.ejb.plugins.StatefulSessionInstanceCache.doActivate(StatefulSessionInstanceCache.java:129) [:6.1.0.Final]
	at org.jboss.ejb.plugins.AbstractInstanceCache.get(AbstractInstanceCache.java:123) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer.getEJBObject(StatefulSessionContainer.java:394) [:6.1.0.Final]
	at sun.reflect.GeneratedMethodAccessor3683.invoke(Unknown Source) [:1.6.0_33]

2012-10-08 05:17:10,491 DEBUG [org.jboss.ejb.plugins.AbstractInstanceCache] (WorkerThread#5[192.168.20.71:47311])  Activation failure: javax.ejb.EJBException: Could not activate; failed to restore state
	at org.jboss.ejb.plugins.StatefulSessionFilePersistenceManager.activateSession(StatefulSessionFilePersistenceManager.java:343) [:6.1.0.Final]
	at org.jboss.ejb.plugins.StatefulSessionInstanceCache.activate(StatefulSessionInstanceCache.java:113) [:6.1.0.Final]
	at org.jboss.ejb.plugins.AbstractInstanceCache.doActivate(AbstractInstanceCache.java:458) [:6.1.0.Final]
	at org.jboss.ejb.plugins.StatefulSessionInstanceCache.doActivate(StatefulSessionInstanceCache.java:129) [:6.1.0.Final]
	at org.jboss.ejb.plugins.AbstractInstanceCache.get(AbstractInstanceCache.java:123) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer.getEJBObject(StatefulSessionContainer.java:394) [:6.1.0.Final]
	at sun.reflect.GeneratedMethodAccessor3683.invoke(Unknown Source) [:1.6.0_33]

2012-10-08 12:35:00,085 DEBUG [org.hibernate.SQL] (Thread-16926) ::nobody::2724: update offnet.EVENT set ATTEMPTS=?, ERROR_CODE=?, LAST_ATTEMPT=?, LOCK_DATE=?, LOCKED_BY=?, NEXT_ATTEMPT=?, STATE=?, VERSION=? where EVENT_GUID=? and VERSION=?
, callbackMethod=MerchantApiBean.processResponse, errorCode=EVENT_CALLBACK_ERROR, nextAttempt=2012-10-09 12:35:00.084}
	at oracle.jdbc.driver.DatabaseError.throwBatchUpdateException(DatabaseError.java:629) [:Oracle JDBC Driver version - "11.1.0.7.0-Production"]
	at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:9409) [:Oracle JDBC Driver version - "11.1.0.7.0-Production"]
	at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:211) [:Oracle JDBC Driver version - "11.1.0.7.0-Production"]
	at org.jboss.resource.adapter.jdbc.CachedPreparedStatement.executeBatch(CachedPreparedStatement.java:476) [:6.1.0.Final]
	at org.jboss.resource.adapter.jdbc.WrappedStatement.executeBatch(WrappedStatement.java:774) [:6.1.0.Final]
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:70) [:3.6.6.Final]
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:268) [:3.6.6.Final]

2012-10-08 14:00:00,046 DEBUG [org.hibernate.SQL] (Thread-16926) ::nobody::2726: update offnet.EVENT set ATTEMPTS=?, ERROR_CODE=?, LAST_ATTEMPT=?, LOCK_DATE=?, LOCKED_BY=?, NEXT_ATTEMPT=?, STATE=?, VERSION=? where EVENT_GUID=? and VERSION=?
, callbackMethod=MerchantApiBean.processResponse, errorCode=EVENT_CALLBACK_ERROR, nextAttempt=2012-10-09 14:00:00.044}
2012-10-08 14:00:00,050 DEBUG [org.hibernate.SQL] (Thread-16926) ::nobody::2727: select event0_.EVENT_GUID as EVENT1_118_0_, event0_.ATTEMPTS as ATTEMPTS118_0_, event0_.CALLBACK_METHOD as CALLBACK3_118_0_, event0_.ENTRY_DATE as ENTRY4_118_0_, event0_.ERROR_CODE as ERROR5_118_0_, event0_.LAST_ATTEMPT as LAST6_118_0_, event0_.LOCK_DATE as LOCK7_118_0_, event0_.LOCKED_BY as LOCKED8_118_0_, event0_.NEXT_ATTEMPT as NEXT9_118_0_, event0_.PARENT_EVENT_GUID as PARENT10_118_0_, event0_.REQUEST as REQUEST118_0_, event0_.RESPONSE as RESPONSE118_0_, event0_.STATE as STATE118_0_, event0_.TRANSACTION_REF as TRANSAC14_118_0_, event0_.TYPE as TYPE118_0_, event0_.VERSION as VERSION118_0_ from offnet.EVENT event0_ where event0_.EVENT_GUID=?
2012-10-08 14:00:00,055 DEBUG [org.hibernate.SQL] (Thread-16926) ::nobody::2728: select event0_.EVENT_GUID as EVENT1_118_0_, event0_.ATTEMPTS as ATTEMPTS118_0_, event0_.CALLBACK_METHOD as CALLBACK3_118_0_, event0_.ENTRY_DATE as ENTRY4_118_0_, event0_.ERROR_CODE as ERROR5_118_0_, event0_.LAST_ATTEMPT as LAST6_118_0_, event0_.LOCK_DATE as LOCK7_118_0_, event0_.LOCKED_BY as LOCKED8_118_0_, event0_.NEXT_ATTEMPT as NEXT9_118_0_, event0_.PARENT_EVENT_GUID as PARENT10_118_0_, event0_.REQUEST as REQUEST118_0_, event0_.RESPONSE as RESPONSE118_0_, event0_.STATE as STATE118_0_, event0_.TRANSACTION_REF as TRANSAC14_118_0_, event0_.TYPE as TYPE118_0_, event0_.VERSION as VERSION118_0_ from offnet.EVENT event0_ where event0_.EVENT_GUID=?
2012-10-08 14:00:00,068 ERROR [com.riavera.ejb.session.EventDispatcherBean] (Thread-16926) ::nobody::2728: unexpected exception processing callback for event 05BDDE01C0A814472B73D6417B0E428B: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [:1.6.0_33]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at com.riavera.ejb.session.EventDispatcherBean.finishAttempt(EventDispatcherBean.java:438) [:]
	at sun.reflect.GeneratedMethodAccessor4196.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
, callbackMethod=MerchantApiBean.processResponse, errorCode=EVENT_CALLBACK_ERROR, nextAttempt=2012-10-09 14:00:00.074}
2012-10-08 14:00:00,075 DEBUG [org.hibernate.SQL] (Thread-16926) ::nobody::2728: update offnet.EVENT set ATTEMPTS=?, ERROR_CODE=?, LAST_ATTEMPT=?, LOCK_DATE=?, LOCKED_BY=?, NEXT_ATTEMPT=?, STATE=?, VERSION=? where EVENT_GUID=? and VERSION=?
, callbackMethod=MerchantApiBean.processResponse, errorCode=EVENT_CALLBACK_ERROR, nextAttempt=2012-10-09 14:00:00.074}
012-10-08 22:11:40,445 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#0[192.168.20.71:59008]) :miiscan-prod:127.0.0.1:nnapp_core900::::0:  service config: registration_fraud_rating_CC_US default value set - PLEASE FIX!
2012-10-08 22:11:40,590 DEBUG [org.hibernate.SQL] (WorkerThread#0[192.168.20.71:59008])  insert into offnet.EVENT (ATTEMPTS, CALLBACK_METHOD, ENTRY_DATE, ERROR_CODE, LAST_ATTEMPT, LOCK_DATE, LOCKED_BY, NEXT_ATTEMPT, PARENT_EVENT_GUID, REQUEST, RESPONSE, STATE, TRANSACTION_REF, TYPE, VERSION, EVENT_GUID) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2012-10-08 22:15:00,015 DEBUG [org.hibernate.SQL] (Thread-16925) ::nobody::2753: select event0_.EVENT_GUID as EVENT1_118_0_, event0_.ATTEMPTS as ATTEMPTS118_0_, event0_.CALLBACK_METHOD as CALLBACK3_118_0_, event0_.ENTRY_DATE as ENTRY4_118_0_, event0_.ERROR_CODE as ERROR5_118_0_, event0_.LAST_ATTEMPT as LAST6_118_0_, event0_.LOCK_DATE as LOCK7_118_0_, event0_.LOCKED_BY as LOCKED8_118_0_, event0_.NEXT_ATTEMPT as NEXT9_118_0_, event0_.PARENT_EVENT_GUID as PARENT10_118_0_, event0_.REQUEST as REQUEST118_0_, event0_.RESPONSE as RESPONSE118_0_, event0_.STATE as STATE118_0_, event0_.TRANSACTION_REF as TRANSAC14_118_0_, event0_.TYPE as TYPE118_0_, event0_.VERSION as VERSION118_0_ from offnet.EVENT event0_ where event0_.EVENT_GUID=?
2012-10-08 22:15:00,023 DEBUG [org.hibernate.SQL] (Thread-16925) ::nobody::2754: select event0_.EVENT_GUID as EVENT1_118_0_, event0_.ATTEMPTS as ATTEMPTS118_0_, event0_.CALLBACK_METHOD as CALLBACK3_118_0_, event0_.ENTRY_DATE as ENTRY4_118_0_, event0_.ERROR_CODE as ERROR5_118_0_, event0_.LAST_ATTEMPT as LAST6_118_0_, event0_.LOCK_DATE as LOCK7_118_0_, event0_.LOCKED_BY as LOCKED8_118_0_, event0_.NEXT_ATTEMPT as NEXT9_118_0_, event0_.PARENT_EVENT_GUID as PARENT10_118_0_, event0_.REQUEST as REQUEST118_0_, event0_.RESPONSE as RESPONSE118_0_, event0_.STATE as STATE118_0_, event0_.TRANSACTION_REF as TRANSAC14_118_0_, event0_.TYPE as TYPE118_0_, event0_.VERSION as VERSION118_0_ from offnet.EVENT event0_ where event0_.EVENT_GUID=?
2012-10-08 22:15:00,077 DEBUG [org.hibernate.SQL] (Thread-16925) ::nobody::2754: select event0_.EVENT_GUID as EVENT1_118_, event0_.ATTEMPTS as ATTEMPTS118_, event0_.CALLBACK_METHOD as CALLBACK3_118_, event0_.ENTRY_DATE as ENTRY4_118_, event0_.ERROR_CODE as ERROR5_118_, event0_.LAST_ATTEMPT as LAST6_118_, event0_.LOCK_DATE as LOCK7_118_, event0_.LOCKED_BY as LOCKED8_118_, event0_.NEXT_ATTEMPT as NEXT9_118_, event0_.PARENT_EVENT_GUID as PARENT10_118_, event0_.REQUEST as REQUEST118_, event0_.RESPONSE as RESPONSE118_, event0_.STATE as STATE118_, event0_.TRANSACTION_REF as TRANSAC14_118_, event0_.TYPE as TYPE118_, event0_.VERSION as VERSION118_ from offnet.EVENT event0_ where event0_.PARENT_EVENT_GUID=?
2012-10-08 22:30:01,541 DEBUG [org.jboss.ejb.plugins.AbstractInstanceCache] (WorkerThread#5[192.168.20.71:15470])  Activation failure: javax.ejb.EJBException: Could not activate; failed to restore state
	at org.jboss.ejb.plugins.StatefulSessionFilePersistenceManager.activateSession(StatefulSessionFilePersistenceManager.java:343) [:6.1.0.Final]
	at org.jboss.ejb.plugins.StatefulSessionInstanceCache.activate(StatefulSessionInstanceCache.java:113) [:6.1.0.Final]
	at org.jboss.ejb.plugins.AbstractInstanceCache.doActivate(AbstractInstanceCache.java:458) [:6.1.0.Final]
	at org.jboss.ejb.plugins.StatefulSessionInstanceCache.doActivate(StatefulSessionInstanceCache.java:129) [:6.1.0.Final]
	at org.jboss.ejb.plugins.AbstractInstanceCache.get(AbstractInstanceCache.java:123) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer.getEJBObject(StatefulSessionContainer.java:394) [:6.1.0.Final]
	at sun.reflect.GeneratedMethodAccessor3683.invoke(Unknown Source) [:1.6.0_33]
2012-10-08 22:30:01,552 ERROR [org.jboss.ejb.plugins.LogInterceptor] (WorkerThread#5[192.168.20.71:15470])  TransactionRolledbackException in method: public abstract javax.ejb.EJBObject javax.ejb.Handle.getEJBObject() throws java.rmi.RemoteException, causedBy:: java.rmi.NoSuchObjectException: Could not activate; failed to restore state
	at org.jboss.ejb.plugins.AbstractInstanceCache.get(AbstractInstanceCache.java:134) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer.getEJBObject(StatefulSessionContainer.java:394) [:6.1.0.Final]
	at sun.reflect.GeneratedMethodAccessor3683.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at org.jboss.invocation.Invocation.performCall(Invocation.java:386) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer$ContainerInterceptor.invokeHome(StatefulSessionContainer.java:564) [:6.1.0.Final]
2012-10-08 22:43:31,403 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#3[192.168.20.71:33160]) :MIISCAN:127.0.0.1:marciayrc::M4H1J6::0:  unable to find cust user:marciayrcNo such entity!
2012-10-08 22:46:00,226 DEBUG [org.jboss.ejb.plugins.AbstractInstanceCache] (WorkerThread#0[192.168.20.71:33165])  Activation failure: javax.ejb.EJBException: Could not activate; failed to restore state
	at org.jboss.ejb.plugins.StatefulSessionFilePersistenceManager.activateSession(StatefulSessionFilePersistenceManager.java:343) [:6.1.0.Final]
	at org.jboss.ejb.plugins.StatefulSessionInstanceCache.activate(StatefulSessionInstanceCache.java:113) [:6.1.0.Final]
	at org.jboss.ejb.plugins.AbstractInstanceCache.doActivate(AbstractInstanceCache.java:458) [:6.1.0.Final]
	at org.jboss.ejb.plugins.StatefulSessionInstanceCache.doActivate(StatefulSessionInstanceCache.java:129) [:6.1.0.Final]
	at org.jboss.ejb.plugins.AbstractInstanceCache.get(AbstractInstanceCache.java:123) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer.getEJBObject(StatefulSessionContainer.java:394) [:6.1.0.Final]
	at sun.reflect.GeneratedMethodAccessor3683.invoke(Unknown Source) [:1.6.0_33]
2012-10-08 22:46:00,236 DEBUG [org.jboss.ejb.plugins.AbstractInstanceCache] (WorkerThread#0[192.168.20.71:33165])  Activation failure: javax.ejb.EJBException: Could not activate; failed to restore state
	at org.jboss.ejb.plugins.StatefulSessionFilePersistenceManager.activateSession(StatefulSessionFilePersistenceManager.java:343) [:6.1.0.Final]
	at org.jboss.ejb.plugins.StatefulSessionInstanceCache.activate(StatefulSessionInstanceCache.java:113) [:6.1.0.Final]
	at org.jboss.ejb.plugins.AbstractInstanceCache.doActivate(AbstractInstanceCache.java:458) [:6.1.0.Final]
	at org.jboss.ejb.plugins.StatefulSessionInstanceCache.doActivate(StatefulSessionInstanceCache.java:129) [:6.1.0.Final]
	at org.jboss.ejb.plugins.AbstractInstanceCache.get(AbstractInstanceCache.java:123) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer.getEJBObject(StatefulSessionContainer.java:394) [:6.1.0.Final]
	at sun.reflect.GeneratedMethodAccessor3683.invoke(Unknown Source) [:1.6.0_33]
2012-10-08 22:46:00,258 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#0[192.168.20.71:33165])  bad: 
2012-10-08 22:46:00,258 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#0[192.168.20.71:33165])  invalidDataMap: {OPERATIONAL_LOGIN=1015}
2012-10-08 22:46:44,252 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#0[192.168.20.71:33165])  bad: 
2012-10-08 22:46:44,252 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#0[192.168.20.71:33165])  invalidDataMap: {OPERATIONAL_LOGIN=1015}
2012-10-08 22:48:38,990 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#5[192.168.20.71:33438]) :MIISCAN:127.0.0.1:marciayrc::M4H1J6::0:  unable to find cust user:marciayrcNo such entity!
2012-10-08 22:48:39,038 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#5[192.168.20.71:33438]) :MIISCAN:127.0.0.1:marciayrc::M4H1J6::0:  unable to find cust user:marciayrcNo such entity!
2012-10-08 22:51:30,334 DEBUG [org.hibernate.SQL] (WorkerThread#8[192.168.20.71:22841]) ::nnapp_fi_in::2768: insert into offnet.TRANSACTION (CALLER_ID, CARD_TYPE, CLIENT_ADDRESS, COMPLETION_DATE, CUST_ADDRESS1, CUST_ADDRESS2, CUST_CITY, CUST_COUNTRY, CUST_GUID, CUST_NAME_FIRST, CUST_NAME_LAST, CUST_PHONE_NUM, CUST_POSTAL_CODE, CUST_PROVINCE, EMAIL, ENTRY_DATE, ERROR_CODE, EXCHANGE_RATE, INVOICE_NO, IVR_DESCRIPTOR, IVR_NUMBER, LANG_PREF, OPTIONS, POST_PROC_STATE, PRODUCT_PROFILE_GUID, SHOPPER_AMOUNT, SHOPPER_CURRENCY, SITE_PASSWORD, SITE_USERNAME, STATE, TEMP1, TRANSACTION_ID, TRANSACTION_TYPE, USER1, USER2, USER3, USER4, USER5, VENDOR_AMOUNT, VENDOR_C_REDIRECT_URL, VENDOR_CURRENCY, VENDOR_F_REDIRECT_URL, VENDOR_ID, VENDOR_S_REDIRECT_URL, VERSION, TRANSACTION_REF) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2012-10-08 22:51:46,694 DEBUG [org.hibernate.SQL] (WorkerThread#6[192.168.20.71:22845]) ::nnapp_fi_in::2769: select transactio0_.TRANSACTION_REF as TRANSACT1_120_1_, transactio0_.CALLER_ID as CALLER2_120_1_, transactio0_.CARD_TYPE as CARD3_120_1_, transactio0_.CLIENT_ADDRESS as CLIENT4_120_1_, transactio0_.COMPLETION_DATE as COMPLETION5_120_1_, transactio0_.CUST_ADDRESS1 as CUST6_120_1_, transactio0_.CUST_ADDRESS2 as CUST7_120_1_, transactio0_.CUST_CITY as CUST8_120_1_, transactio0_.CUST_COUNTRY as CUST9_120_1_, transactio0_.CUST_GUID as CUST10_120_1_, transactio0_.CUST_NAME_FIRST as CUST11_120_1_, transactio0_.CUST_NAME_LAST as CUST12_120_1_, transactio0_.CUST_PHONE_NUM as CUST13_120_1_, transactio0_.CUST_POSTAL_CODE as CUST14_120_1_, transactio0_.CUST_PROVINCE as CUST15_120_1_, transactio0_.EMAIL as EMAIL120_1_, transactio0_.ENTRY_DATE as ENTRY17_120_1_, transactio0_.ERROR_CODE as ERROR18_120_1_, transactio0_.EXCHANGE_RATE as EXCHANGE19_120_1_, transactio0_.INVOICE_NO as INVOICE20_120_1_, transactio0_.IVR_DESCRIPTOR as IVR21_120_1_, transactio0_.IVR_NUMBER as IVR22_120_1_, transactio0_.LANG_PREF as LANG23_120_1_, transactio0_.OPTIONS as OPTIONS120_1_, transactio0_.POST_PROC_STATE as POST25_120_1_, transactio0_.PRODUCT_PROFILE_GUID as PRODUCT26_120_1_, transactio0_.SHOPPER_AMOUNT as SHOPPER27_120_1_, transactio0_.SHOPPER_CURRENCY as SHOPPER28_120_1_, transactio0_.SITE_PASSWORD as SITE29_120_1_, transactio0_.SITE_USERNAME as SITE30_120_1_, transactio0_.STATE as STATE120_1_, transactio0_.TEMP1 as TEMP32_120_1_, transactio0_.TRANSACTION_ID as TRANSAC33_120_1_, transactio0_.TRANSACTION_TYPE as TRANSAC34_120_1_, transactio0_.USER1 as USER35_120_1_, transactio0_.USER2 as USER36_120_1_, transactio0_.USER3 as USER37_120_1_, transactio0_.USER4 as USER38_120_1_, transactio0_.USER5 as USER39_120_1_, transactio0_.VENDOR_AMOUNT as VENDOR40_120_1_, transactio0_.VENDOR_C_REDIRECT_URL as VENDOR41_120_1_, transactio0_.VENDOR_CURRENCY as VENDOR42_120_1_, transactio0_.VENDOR_F_REDIRECT_URL as VENDOR43_120_1_, transactio0_.VENDOR_ID as VENDOR44_120_1_, transactio0_.VENDOR_S_REDIRECT_URL as VENDOR45_120_1_, transactio0_.VERSION as VERSION120_1_, transactio1_.TRANSACTION_REF as TRANSACT2_120_3_, transactio1_.PARAMETER as PARAMETER3_, transactio1_.TRANSACTION_REF as TRANSACT2_3_, transactio1_.PARAMETER as PARAMETER111_0_, transactio1_.TRANSACTION_REF as TRANSACT2_111_0_, transactio1_.DATE_VALUE as DATE3_111_0_, transactio1_.STR_VALUE as STR4_111_0_ from offnet.TRANSACTION transactio0_ left outer join offnet.TRANSACTION_XREF transactio1_ on transactio0_.TRANSACTION_REF=transactio1_.TRANSACTION_REF where transactio0_.TRANSACTION_REF=?
2012-10-08 22:51:46,713 DEBUG [org.jboss.ejb.plugins.cmp.jdbc.JDBCLoadEntityCommand.Transaction] (WorkerThread#3[192.168.20.71:33443]) :MobileWallet:127.0.0.1:nnapp_fi_in::::0:  Executing SQL: SELECT TRANSACTION_ID, VERSION, TRANSACTION_TYPE, STATE, ENTRY_DATE, COMPLETION_DATE, VENDOR_ID, VENDOR_S_REDIRECT_URL, VENDOR_C_REDIRECT_URL, VENDOR_F_REDIRECT_URL, INVOICE_NO, VENDOR_CURRENCY, VENDOR_AMOUNT, EXCHANGE_RATE, SHOPPER_CURRENCY, SHOPPER_AMOUNT, CARD_TYPE, IVR_NUMBER, SITE_USERNAME, SITE_PASSWORD, CALLER_ID, CLIENT_ADDRESS, USER1, USER2, USER3, USER4, USER5, OPTIONS, EMAIL, TEMP1, IVR_DESCRIPTOR, CUST_PHONE_NUM, LANG_PREF, CUST_GUID, PRODUCT_PROFILE_GUID, POST_PROC_STATE, CUST_NAME_FIRST, CUST_NAME_LAST, CUST_ADDRESS1, CUST_ADDRESS2, CUST_CITY, CUST_PROVINCE, CUST_COUNTRY, CUST_POSTAL_CODE, ERROR_CODE FROM offnet.TRANSACTION WHERE (TRANSACTION_REF=?)
2012-10-08 22:51:47,009 DEBUG [org.jboss.ejb.plugins.cmp.jdbc.JDBCStoreEntityCommand.Transaction] (WorkerThread#3[192.168.20.71:33443]) ::nnapp_fi_in::2770: Executing SQL: UPDATE offnet.TRANSACTION SET ERROR_CODE=? WHERE TRANSACTION_REF=?
2012-10-08 22:51:47,026 DEBUG [org.jboss.ejb.plugins.cmp.jdbc.JDBCLoadEntityCommand.Transaction] (WorkerThread#3[192.168.20.71:33443]) :MobileWallet:127.0.0.1:nnapp_fi_in::::0:  Executing SQL: SELECT TRANSACTION_ID, VERSION, TRANSACTION_TYPE, STATE, ENTRY_DATE, COMPLETION_DATE, VENDOR_ID, VENDOR_S_REDIRECT_URL, VENDOR_C_REDIRECT_URL, VENDOR_F_REDIRECT_URL, INVOICE_NO, VENDOR_CURRENCY, VENDOR_AMOUNT, EXCHANGE_RATE, SHOPPER_CURRENCY, SHOPPER_AMOUNT, CARD_TYPE, IVR_NUMBER, SITE_USERNAME, SITE_PASSWORD, CALLER_ID, CLIENT_ADDRESS, USER1, USER2, USER3, USER4, USER5, OPTIONS, EMAIL, TEMP1, IVR_DESCRIPTOR, CUST_PHONE_NUM, LANG_PREF, CUST_GUID, PRODUCT_PROFILE_GUID, POST_PROC_STATE, CUST_NAME_FIRST, CUST_NAME_LAST, CUST_ADDRESS1, CUST_ADDRESS2, CUST_CITY, CUST_PROVINCE, CUST_COUNTRY, CUST_POSTAL_CODE, ERROR_CODE FROM offnet.TRANSACTION WHERE (TRANSACTION_REF=?)
2012-10-08 23:08:02,705 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#0[192.168.20.71:9724])  bad: 
2012-10-08 23:08:02,705 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#0[192.168.20.71:9724])  invalidDataMap: {HOME_PHONE=45016}
2012-10-08 23:09:34,205 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#0[192.168.20.71:9724]) :miiscan-prod:127.0.0.1:nnapp_core900::::0:  unable to find country native currency!: javax.ejb.ObjectNotFoundException: No such entity!
	at org.jboss.ejb.plugins.cmp.jdbc.JDBCFindEntityCommand.execute(JDBCFindEntityCommand.java:64) [:6.1.0.Final]
	at org.jboss.ejb.plugins.cmp.jdbc.JDBCStoreManager.findEntity(JDBCStoreManager.java:604) [:6.1.0.Final]
	at org.jboss.ejb.plugins.CMPPersistenceManager.findEntity(CMPPersistenceManager.java:315) [:6.1.0.Final]
	at org.jboss.resource.connectionmanager.CachedConnectionInterceptor.findEntity(CachedConnectionInterceptor.java:234) [:6.1.0.Final]
	at org.jboss.ejb.EntityContainer.findSingleObject(EntityContainer.java:1117) [:6.1.0.Final]
	at org.jboss.ejb.EntityContainer.findLocal(EntityContainer.java:689) [:6.1.0.Final]
	at sun.reflect.GeneratedMethodAccessor3498.invoke(Unknown Source) [:1.6.0_33]
2012-10-08 23:09:34,212 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#0[192.168.20.71:9724]) :miiscan-prod:127.0.0.1:nnapp_core900::::0:  unknown exception:: com.navahonetworks.exceptions.NNIllegalArgumentException: Country currency not found
	at com.navahonetworks.ejb.session.app.CoreAppUseBean.oldRegisterCust(CoreAppUseBean.java:1670) [:]
	at com.navahonetworks.ejb.session.app.CoreAppUseBean.registerCust(CoreAppUseBean.java:216) [:]
	at sun.reflect.GeneratedMethodAccessor5594.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at org.jboss.invocation.Invocation.performCall(Invocation.java:386) [:6.1.0.Final]
	at org.jboss.ejb.StatelessSessionContainer$ContainerInterceptor.invoke(StatelessSessionContainer.java:233) [:6.1.0.Final]
2012-10-08 23:10:51,840 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#5[192.168.20.71:9729]) :miiscan-prod:84.46.117.83:n.roloff@hotmail.de::::0:  unable to find cust user:n.roloff@hotmail.deNo such entity!
2012-10-08 23:11:09,350 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#5[192.168.20.71:9729]) :miiscan-prod:84.46.117.83:n.roloff@hotmail.de::::0:  unable to find cust user:n.roloff@hotmail.deNo such entity!
2012-10-08 23:11:31,748 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#5[192.168.20.71:9729]) :miiscan-prod:84.46.117.83:n.roloff@hotmail.de::::0:  unable to find cust user:n.roloff@hotmail.deNo such entity!
2012-10-08 23:12:06,339 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#5[192.168.20.71:9729]) :miiscan-prod:84.46.117.83:niklas::::0:  unable to find cust user:niklasNo such entity!
2012-10-08 23:13:59,316 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#3[192.168.20.71:25829])  bad: HOME_NAME_PREFIX 
2012-10-08 23:13:59,316 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#3[192.168.20.71:25829])  invalidDataMap: {HOME_NAME_PREFIX=45001}
2012-10-08 23:14:29,108 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#3[192.168.20.71:25829])  bad: HOME_NAME_PREFIX 
2012-10-08 23:14:29,108 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#3[192.168.20.71:25829])  invalidDataMap: {HOME_NAME_PREFIX=45001}
2012-10-08 23:17:02,839 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#0[192.168.20.71:33256]) :MIISCAN:127.0.0.1:niklas roloff::M4H1J6::0:  unable to find cust user:niklas roloffNo such entity!
2012-10-08 23:17:31,416 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#0[192.168.20.71:33256]) :MIISCAN:127.0.0.1:n.roloff@hotmail.de::M4H1J6::0:  unable to find cust user:n.roloff@hotmail.deNo such entity!
2012-10-08 23:17:33,797 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#0[192.168.20.71:33256]) :MIISCAN:127.0.0.1:n.roloff@hotmail.de::M4H1J6::0:  unable to find cust user:n.roloff@hotmail.deNo such entity!
